name: fair_share
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

workspace:
  - packages/shared_ui
  - packages/design_system
  - packages/shared_core

dependencies:
  auto_route: ^11.1.0
  dartz: ^0.10.1
  easy_localization: ^3.0.8
  firebase_core: any
  firebase_crashlytics: any
  firebase_auth: any
  cloud_firestore: any
  firebase_messaging: any
  flutter:
    sdk: flutter
  flutter_flavor: ^3.1.4
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.3.1
  get_it: ^7.7.0
  hooks_riverpod: any
  http: ^1.2.0
  logger: ^2.7.0
  mason: ^0.1.2
  riverpod_annotation: any
  shared_core: any
  shared_ui: any
  equatable: ^2.0.6
  json_annotation: ^4.9.0
  copy_with_extension: any
  freezed_annotation: ^3.1.0
  uuid: ^4.6.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  flutter_native_splash: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  clean_architecture_with_state_management:
  auto_route_generator: 10.4.0
  build_runner: ^2.4.11
  riverpod_generator: any
  json_serializable: ^6.8.0
  copy_with_extension_gen: any
  mocktail: ^1.0.4
  melos: ^7.0.0-dev.9
  patrol: ^4.6.1
  patrol_finders: ^3.5.0
  integration_test:
    sdk: flutter
  freezed: ^3.2.5


flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icon/

flutter_native_splash:
  color: "#00655C"
  image: assets/icon/splash_icon.png
  android_12:
    image: assets/icon/splash_icon.png
    color: "#00655C"



patrol: 
  app_name: "Fair Share"
  test_directory: integration_test
