// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmrEfWEM6ggrtEihO6Ft7eGNHnJga0Daw',
    appId: '1:246268639930:web:c173866b667fa400abe083',
    messagingSenderId: '246268639930',
    projectId: 'fairshare-ffea8',
    authDomain: 'fairshare-ffea8.firebaseapp.com',
    storageBucket: 'fairshare-ffea8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcqEchOZqdJbSLYrvGV83Wva8kbKlMhLA',
    appId: '1:246268639930:android:4d3a28fe77a2ba42abe083',
    messagingSenderId: '246268639930',
    projectId: 'fairshare-ffea8',
    storageBucket: 'fairshare-ffea8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUMH1XIociFYjBTbMu2ITANKNdeGtGwms',
    appId: '1:246268639930:ios:7d3f47b00cdd1132abe083',
    messagingSenderId: '246268639930',
    projectId: 'fairshare-ffea8',
    storageBucket: 'fairshare-ffea8.firebasestorage.app',
    iosBundleId: 'com.example.fairShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUMH1XIociFYjBTbMu2ITANKNdeGtGwms',
    appId: '1:246268639930:ios:7d3f47b00cdd1132abe083',
    messagingSenderId: '246268639930',
    projectId: 'fairshare-ffea8',
    storageBucket: 'fairshare-ffea8.firebasestorage.app',
    iosBundleId: 'com.example.fairShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmrEfWEM6ggrtEihO6Ft7eGNHnJga0Daw',
    appId: '1:246268639930:web:4b7a74e8889a63a2abe083',
    messagingSenderId: '246268639930',
    projectId: 'fairshare-ffea8',
    authDomain: 'fairshare-ffea8.firebaseapp.com',
    storageBucket: 'fairshare-ffea8.firebasestorage.app',
  );
}
